# Multimodal Fusion Model Configuration
# Defines the architecture for combining vision and text features

# Model Architecture
model:
  name: "multimodal_fusion"
  
  # Vision branch
  vision:
    backbone: "yolov8_backbone"  # Use features from YOLOv8 backbone
    feature_dim: 512
    pooling: "adaptive_avg"  # adaptive_avg, adaptive_max, global_avg
    
  # Text branch
  text:
    embedder: "sentence-transformers/all-MiniLM-L6-v2"
    feature_dim: 384
    max_length: 128
    
  # Fusion methods (implement both)
  fusion:
    # Method A: Concatenation (for edge deployment)
    concatenation:
      enabled: true
      hidden_dims: [512, 256, 128]
      dropout: 0.2
      activation: "relu"
    
    # Method B: Cross-attention (for cloud deployment)
    cross_attention:
      enabled: true
      num_heads: 8
      hidden_dim: 512
      num_layers: 2
      dropout: 0.1
      
  # Output heads
  heads:
    classification:
      num_classes: 10
      dropout: 0.3
      
    severity:
      type: "regression"  # regression, ordinal
      output_dim: 1
      activation: "sigmoid"
      
    confidence:
      output_dim: 1
      activation: "sigmoid"

# Training Configuration
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  
  # Loss weights
  loss_weights:
    classification: 1.0
    severity: 0.5
    confidence: 0.3
    
  # Optimizer
  optimizer: "AdamW"
  scheduler: "cosine"
  
  # Early stopping
  early_stopping:
    patience: 15
    min_delta: 0.001

# Data Configuration
data:
  # Vision data
  vision:
    train_path: "data/annotated/instances_train.json"
    val_path: "data/annotated/instances_val.json"
    image_size: [640, 640]
    
  # Text data (farmer notes)
  text:
    train_path: "data/annotated/farmer_notes_train.json"
    val_path: "data/annotated/farmer_notes_val.json"
    max_length: 128
    
  # Fusion data (paired vision-text)
  fusion:
    train_path: "data/annotated/fusion_train.json"
    val_path: "data/annotated/fusion_val.json"

# Validation Configuration
validation:
  metrics:
    - "accuracy"
    - "f1_score"
    - "severity_mae"
    - "confidence_auc"
    
  # Calibration
  calibration:
    enabled: true
    method: "temperature_scaling"
    validation_split: 0.2

# Export Configuration
export:
  formats:
    - "onnx"
    - "tensorrt"
    - "tflite"
    
  # Edge optimization
  optimization:
    quantization: true
    pruning: false
    distillation: false

# Logging
logging:
  log_dir: "logs/fusion_training"
  wandb:
    enabled: true
    project: "agrispray-ai-fusion"
  mlflow:
    enabled: true
    experiment_name: "multimodal_fusion"
