# Dose Optimization Configuration
# Defines parameters for pesticide dose optimization

# Optimization Method
optimization:
  primary_solver: "cvxpy"  # cvxpy, ortools
  fallback_solver: "milp"  # milp for discrete constraints
  
  # CVXPY Configuration
  cvxpy:
    solver: "OSQP"  # OSQP, ECOS, SCS
    max_iter: 10000
    eps_abs: 1e-6
    eps_rel: 1e-6
    verbose: false
    
  # MILP Configuration (OR-Tools)
  milp:
    solver: "CBC"  # CBC, SCIP, Gurobi
    time_limit: 300  # seconds
    gap_limit: 0.01  # 1% optimality gap

# Dose-Cure Model Parameters
dose_cure_model:
  # P_cure(d, s) = sigmoid(a(s) * d + b(s))
  # Parameters fitted from literature/field trials
  parameters:
    # Severity 0 (healthy)
    0:
      a: 0.1
      b: -2.0
    # Severity 1 (mild)
    1:
      a: 0.2
      b: -1.5
    # Severity 2 (moderate)
    2:
      a: 0.4
      b: -1.0
    # Severity 3 (severe)
    3:
      a: 0.8
      b: -0.5
      
  # Fallback conservative parameters
  fallback:
    a: 0.5
    b: -1.0

# Optimization Constraints
constraints:
  # Target cure probability
  target_cure_prob: 0.85
  
  # Per-plant dose limits (ml)
  per_plant:
    min_dose: 0.0
    max_dose: 50.0
    
  # Area-wide dose limits (ml per m²)
  area:
    max_dose_per_m2: 100.0
    
  # Regulatory limits
  regulatory:
    max_total_dose: 1000.0  # ml per field
    max_concentration: 0.1  # % active ingredient

# Safety Configuration
safety:
  # Confidence thresholds
  confidence_threshold: 0.80
  
  # Operator approval required for:
  approval_required:
    - "confidence < 0.80"
    - "regulatory_exceedance"
    - "dose > 2x_baseline"
    
  # Logging requirements
  logging:
    immutable_logs: true
    log_all_decisions: true
    retention_days: 365

# UAV/Actuator Configuration
actuator:
  # Nozzle specifications
  nozzle:
    flow_rate: 2.0  # ml/s
    efficiency: 0.85  # 85% efficiency
    min_on_time: 0.1  # seconds
    max_on_time: 10.0  # seconds
    
  # Flight parameters
  flight:
    speed: 5.0  # m/s
    altitude: 2.0  # m
    overlap: 0.1  # 10% overlap
    
  # Discrete constraints (for MILP)
  discrete:
    waypoint_spacing: 1.0  # m
    min_spray_duration: 0.5  # seconds
    max_spray_duration: 5.0  # seconds

# Performance Targets
performance:
  # Optimization time limits
  time_limits:
    cvxpy: 10.0  # seconds
    milp: 60.0  # seconds
    
  # Solution quality
  quality:
    optimality_gap: 0.05  # 5%
    feasibility_tolerance: 1e-6
    
  # Pesticide reduction targets
  reduction_target: 0.30  # 30% reduction vs uniform spray

# Monitoring and Logging
monitoring:
  log_dir: "logs/optimization"
  
  # Metrics to track
  metrics:
    - "optimization_time"
    - "solution_quality"
    - "dose_reduction"
    - "constraint_violations"
    
  # Alerts
  alerts:
    optimization_failure: true
    constraint_violation: true
    high_dose_usage: true
