# YOLOv8 Baseline Configuration for AgriSprayAI
# This config defines the baseline detector for pest/disease detection

# Model Configuration
model:
  name: "yolov8n"  # Start with nano for baseline, progress to medium/large
  input_size: [640, 640]
  num_classes: 12  # Agricultural pests dataset: ants, bees, beetle, catterpillar, earthworms, earwig, grasshopper, moth, slug, snail, wasp, weevil
  severity_head: true  # Custom head for severity prediction (0-3)

# Training Configuration
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.01
  weight_decay: 0.0005
  momentum: 0.937
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  
  # Multi-task loss weights
  loss_weights:
    detection: 1.0
    segmentation: 0.5
    classification: 1.0
    severity: 0.3

# Data Configuration
data:
  train_path: "data/annotated/instances_train.json"
  val_path: "data/annotated/instances_val.json"
  test_path: "data/annotated/instances_test.json"
  images_dir: "data/raw/organized/images"
  
  # COCO format with custom severity field
  format: "coco"
  custom_fields:
    - "severity"  # Integer 0-3 for disease severity
  
  # Augmentation
  augmentation:
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0

# Validation Configuration
validation:
  metrics:
    - "mAP@0.5"
    - "mAP@0.5:0.95"
    - "precision"
    - "recall"
    - "severity_mae"  # Mean Absolute Error for severity prediction
  
  # Target performance
  targets:
    map_50: 0.65
    map_50_95: 0.45
    severity_mae: 0.5

# Optimization Configuration
optimization:
  optimizer: "SGD"
  scheduler: "cosine"
  early_stopping:
    patience: 20
    min_delta: 0.001
  
  # Mixed precision training
  mixed_precision: true
  
  # Gradient clipping
  gradient_clip: 10.0

# Model Export Configuration
export:
  formats:
    - "onnx"
    - "tensorrt"
    - "tflite"
  
  # Quantization for edge deployment
  quantization:
    onnx: true
    tflite: true
    tensorrt: true
  
  # Optimization for edge
  optimization_level: "O3"

# Logging and Monitoring
logging:
  log_dir: "logs/training"
  log_interval: 100
  save_interval: 10
  
  # Weights & Biases integration
  wandb:
    enabled: true
    project: "agrispray-ai"
    entity: "your-entity"
  
  # MLflow integration
  mlflow:
    enabled: true
    experiment_name: "yolov8_baseline"

# Hardware Configuration
hardware:
  device: "auto"  # auto, cpu, cuda, mps
  num_workers: 4
  pin_memory: true
  
  # Multi-GPU training
  distributed:
    enabled: false
    backend: "nccl"
